token_ttl: 48h
secret: "akjsdjnvljkldjhfljakwenrjkhelrj34kn5n5kljl"
app:
  port: 8080
  addr: "0.0.0.0"
  machine_local_addr: "192.168.113.215" # It will be used to generate a correct qr-code
postgres:
  addr: "storage"
  port: 5432
  user: "postgres"
  password: "postgres"
  db: "sharing_machines"
  conn_time_exceed: 3s # time duration to try connect to db
# settings for microcontroller (arduino)
mc:
  request_timeout: 1s

log:
  out_dir: "logs"
  dev: "dev_logs.log"
  csv: "sessions.csv" 
